### ISSUE TITLE
INA219 configuration is not what it seems to be

### ISSUE THREAD

**Issue by hogthrob** [thomastech/Sparky#2]
The resulting configuration of the INA219 is not what it seems to be:

https://github.com/thomastech/Sparky/blob/9c30f25622108ede3e594dfe7e055e36fbda316d/src/PulseWelder/src/measure.cpp#L62

generates as IN219 config register value 0x183F or
in bit groups:  000 11 0000 0111 111
BRNG = 0 -> 16V
PG10 = 11 -> /8 320mV
BADC = 0000 -> 9 bit, 84uS
SADC = 0111 -> 12 bit, 532uS 
MODE = 111 -> Continuous Shunt and Bus voltage 

Reason for this is the extensive use of default values combined with limited checking of value ranges in the INA219 library used. 

```
void configure(uint8_t range = D_RANGE, uint8_t gain = D_GAIN, uint8_t bus_adc = D_BUS_ADC, uint8_t shunt_adc = D_SHUNT_ADC, uint8_t mode = D_MODE);
```
So the correct call to achieve the intentions would be:
```
ina219.configure(BUS_RANGE_16V,  PGA_RANGE_160MV, 0, SAMPLE_AVG_128, CONTINUOS_OP);
```
The extra 0 for the bus_adc shifts the shunt_adc setting to the right place.

Unfortunately this alone would not work as expected, as SAMPLE_AVG_128 is set to 16 (0b10000) but should be 15 ( 0b1111). Because of the missing checking of value ranges in configure, the 5th bit "bleeds" into the next higher settings bits.  So SAMPLE_AVG_128 has to be defined to 15 in PulseWelder.h

However, I wonder, if we should not simply fix the configuration call to match what has been configured in reality, e.g. like this (given set the used defines to the correct values)
```
ina219.configure(BUS_RANGE_16V,  PGA_RANGE_320MV, SAMPLE_9BITS, SAMPLE_12BITS, CONTINUOS_OP);
```
and start from there. For things I have in mind, the averaging in the INA219 may not be appropriate, I have to see what current sample rate I will need. 

BTW, the config register value generated from this is 0x181F which is identical in terms of resulting configuration to 0x183F since the 3rd bit in SAMPLE_12BITS is don't care if the 4th( == MSB) bit is 0.

If this is fine with everyone, I would submit a PR for this.

**Comment by thomastech** [comment]
@hogthrob, thanks for your investigation info. You mentioned that your revised code creates the same effective register value (was 0x183F, now  0x181F) as the original code. Is that correct?

Regarding validation, have you tested your code changes on the welder while burning a rod? Is the displayed real-time Amps behaving the same? That is to say, same measured value and not excessively bouncing around.

- Thomas

**Comment by hogthrob** [comment]
Was correct (0x181F). Now after calculating the max current with the 160mv range and a 0.525 mOhm resistor to be well above 200A, I switched my mind and  left the 160mV range setting in the configure call, which changes the config value to 0x101F (meaning it now actually activates the 160mV range).

**Comment by hogthrob** [comment]
Regarding validation, I am still in the progress of building and testing the electronics separated from the actual welder in a test bed. JST XH 7p needs to arrive before I can put things together. I will also need to reprint the electronics case, as I will use connectors on the PCB which require 5mm higher clearance from the PCB to the ZX7 case. BTW, I printed the original case for electronics and speaker and these work fine (if using soldered connections).

**Comment by thomastech** [comment]
> I switched my mind and left the 160mV range setting in the configure call, which changes the config value to 0x101F (meaning it now actually activates the 160mV range).

For sure the 160mV range would be preferred (versus 320mV).

Regarding validation, I've put it on my to-do list too. I have another project in the way so there will be a delay. This PR isn't an urgent issue so immediate action isn't needed. And it will give you a chance to finish up your welder and check things out.

- Thomas

**Comment by hogthrob** [comment]
I started to connect welder and control (not the potentiometer yet, will get the 7p connector tomorrow). 

Current measurement works. I needed to adjust the shunt resistance value to 0.375 mOhm in order to have a match between my clamp current meter and the displayed value
Voltage measurement is shaky, Looking at the voltage waveform this is no surprise, there is a huge oscillation every 10uS. I guess this is when the inverter PWM turns on (or off). Samples taken at this time are way off. Do you have the same experience?

BTW, I implemented a full shutdown feature using the shutdown pin (pin 10) of the PWM controller. Lifting this pin from the pad (so that the pin is no longer connected to anything) and then connecting it to an GPIO of the ESP32 (I used GPIO15). 

See https://github.com/hogthrob/Sparky/commit/ba7d25146728398ea5abdeeb6eacf17be10e48f1

**Comment by thomastech** [comment]
> Current measurement works. I needed to adjust the shunt resistance value to 0.375 mOhm in order to have a match between my clamp current meter and the displayed value.

Your 0.375 mOhm shunt value is vastly different from the 0.525 mOhm needed on my welder. Rather than ignore this, I think it needs investigation.  I have some questions:
(1) If you revert your INA219 code changes does the original shunt value become a more reasonable match?
(2) Do the welder's Vin sense wire attachment points (from the INA219) match the details from the main controller PCB photos shown on the build blog? 
(3) What is the maximum _short circuit_ current that is measured by the clamp meter on your welder? 

> Voltage measurement is shaky, Looking at the voltage waveform this is no surprise, there is a huge oscillation every 10uS. I guess this is when the inverter PWM turns on (or off). Samples taken at this time are way off. Do you have the same experience?

My welder's OC voltage (~60V) measurement is stable. It varies (20V-30V) while burning a rod, as expected. If your OC voltage varies then that probably deserves investigation. Check the R1/R2 attenuator filter Cap C1 (0.47uF). It should be directly soldered to ESP32 Pin-3 and a nearby ground. The attenuator resistor pair is mounted on the main controller board (see build log photos).

> BTW, I implemented a full shutdown feature using the shutdown pin (pin 10) of the PWM controller. Lifting this pin from the pad (so that the pin is no longer connected to anything) and then connecting it to an GPIO of the ESP32 (I used GPIO15).

That's a nice hardware hack. Thanks for sharing!

BTW, it would be convenient to other builders if hardware troubleshooting / modifications are discussed at the rc-cam build blog. That is to say, use Sparky's github site for coding issues and the rc-cam blog for hardware discussions.
Direct link to blog: https://www.rc-cam.com/forum/index.php?/topic/4605-sparky-a-little-stick-welder-with-big-features/

- Thomas

**Comment by hogthrob** [comment]
I soldered all the wires in virtually the same location as on the screenshots.

INA219:
Original code has exactly the same values for current and voltage, hence I continued to work with my new code. 

By using the blue potentiometer one can control the current range of the inverter. I set this to very low initial current, so that I could verify my readings  not only with a clamp meter but a normal 10A meter as well. It is all consistent with the 0.375 mOhm. Might be a production variation. 

BTW, my original current out-of-factory settings where: Lowest achievable current: 45 A, highest current 138A. With the blue trimmer potentiometer I can set this range to 0.2A / 94A. Haven't tried what happens if I go over 45A min current. Seems that there is roughly a range of 90-94 A one can control with the original potentiometer. I still have the inverter in its original condition, i.e. no copper bus bar for the positive side. 
 
Voltage: You were right, I was missing the correctly valued capacitor (47n is not enough :-( ) Now looks stable on the display. So far it looks pretty good now.

I finally received the 7p connectors and (almost) finished the build, I still have to fit the OC LED opto coupler but this is not relevant for testing. 

So I was able to actually use the device for welding.  Measured current (clamp meter) and displayed current seemed to be consistent. A little lower than the set current, which is to be expected, since the potentiometer was "calibrated" using a short circuit with a big screw as ballast.

I confirmed that the MCP41HV51 works "in the wild".

**Comment by thomastech** [comment]
Thanks for the update.  

> ... it is all consistent with the 0.375 mOhm. Might be a production variation.

This is a bargain priced made-in-China product, so anything is possible.

> BTW, my original current out-of-factory settings where: Lowest achievable current: 45 A, highest current 138A. With the blue trimmer potentiometer I can set this range to 0.2A / 94A.

I plan to add trimmer adjustment instructions to the Sparky Blog. I think a 20A low end would be reasonable since that is the MiniBG Welder's advertised spec. 

> Voltage: You were right, I was missing the correctly valued capacitor

Glad to hear you solved the unstable voltage issue.

> I still have to fit the OC LED opto coupler but this is not relevant for testing.

FWIW, the OC LED is somewhat of a mystery. I casually assumed it was the Over-Current warning. But since over-current is an unlikely event, I decided it is actually Over-Temperature (OC = chinglish for Over-Centigrade). There is a third possible usage, the LED might be shared by both of these warnings. Regardless, Sparky's voice will announce it as a "Over-Heat Alarm."

> So I was able to actually use the device for welding. Measured current (clamp meter) and displayed current seemed to be consistent. {snip} I confirmed that the MCP41HV51 works "in the wild".

Fantastic! Thanks for the SPI chip validation feedback.

I've incorporated your two PR changes and the PWM Shutdown feature into my private master branch. I've lightly modified what you provided (minor edits, added PWM shutdown as a user option in config.h. It compiles, so the next task is to perform a validation. Should get that done in a few days, then will formally commit it.

FedEx delivered a portable welding table this morning. Thanks to a 25% off coupon from Harbor Freight. Haven't opened the box yet.

- Thomas

**Comment by thomastech** [comment]
@hogthrob, I started validation and so far have found a couple small issues that will also affect your forked github's screen.cpp file. I can't create a issue ticket on your repository so here's my edits.

**Issue 1**, checkAndUpdateEEPROM(). Fix logged E2Prom Address value.
`
   Serial.println("Write E2Prom Addr: " + String(addr) + ", " + label + ": " + (valueString == NULL?String(value) : valueString));`

**Issue 2**, processScreen(), Fix missing Shutdown pin updates (use new functions to do this).
```
      {                                                     // toggle Arc Current
        arcSwitch = arcSwitch == ARC_ON ? ARC_OFF : ARC_ON; // Pseudo Boolean Toggle.
        drawHomePage();

        if (arcSwitch == ARC_ON) {
          enableArc(true);
          if (spkrVolSwitch != VOL_OFF) {
            DacAudio.Play(&highBeep, true);
          }
        }
        else {
          disableArc(true);
          if (spkrVolSwitch != VOL_OFF) {
            DacAudio.Play(&lowBeep, true);
          }
        }
        previousEepMillis = millis();
        eepromActive      = true; // Request EEProm Write after timer expiry.
      }
```

I will continue the validation tomorrow. Should be done later this week.

- Thomas

**Comment by hogthrob** [comment]
Thank you!

I enabled pull requests and issues for my fork, just in case.

Issue 1: I fixed that, wasn't too hard ;-)

Issue 2:

Instead of using the individual functions, my original code calls controlArc, which combines enable and disableArc.
See here:

https://github.com/hogthrob/Sparky/blob/ba7d25146728398ea5abdeeb6eacf17be10e48f1/src/PulseWelder/src/screen.cpp#L294

Maybe a merge issue.

**Comment by thomastech** [comment]
Issue 2:
Good idea. I've edited the master validation branch, now using controlArc too (instead of the two "primitive" functions).

BTW, be sure to update MIN_AMPS (in config.h) if you have re-calibrated the blue trimmer pot; MIN_AMPS should match the new low end current.

- Thomas

**Comment by thomastech** [comment]
@hogthrob, validation should be done late today.  I'll hold off on a public release in case any last minute issues are submitted. Release is expected in a few days.

All of your suggestions have been incorporated, including the checkAndUpdateEEPROM() function and IS_IN_BOX() macro. I used your PR's as a reference, but made minor changes. So the resulting code isn't an exact match to yours. But close enough.  

I've added a few of my own improvements too. Nothing earth shattering, just little things to help make Sparky even better.

Most importantly, Thank You for your contributions. I appreciate that you shared your ideas.

- Thomas

**Comment by thomastech** [comment]
@hogthrob: Sparky V1.1 has been released.  It would be fantastic if you cloned it and tested with your SPI MCP41HV51 Dig Pot chip (mine has a i2c MCP45HV51).

BTW, the PulseWelder.cpp file includes a revision change list. Several things have been added/altered as summarized in the rev notes.

- Thomas

**Comment by hogthrob** [comment]
I tested v1.1 and is does have a small issue from not fully merging my changes, but this is easy to fix.


What is problematic with the current content in the repo from my point of view is the inclusion of content in the .pio, as this is normally populated by platformio automatically. 

I basically had to use a different git repo checkout in order to avoid manually fixing a lot of merge conflicts.

**Comment by thomastech** [comment]
> I tested v1.1 and is does have a small issue from not fully merging my changes, but this is easy to fix.

Thanks for the feedback.  I will merge your change.

> What is problematic with the current content in the repo from my point of view is the inclusion of content in the .pio, as this is normally populated by platformio automatically.

No problem, I will remove the .pio content from the repo.

- Thomas

**Comment by thomastech** [comment]
Repo has been updated (digPot.cpp merge and .pio folder removal).  If it looks OK to you then let me know so I can close this ticket.

- Thomas

**Comment by hogthrob** [comment]
@thomastech: Thanks! 

It seems that  your .vscode/extensions.json is also causing trouble on Windows (different line endings).
I think we should add .vscode to gitignore (and remove .vscode/extensions.json (but I have no idea what this file is good for).
Apart from that it works.
One question: why did you add the local copies of the INA219, BLE and XT libs. I saw you change something the BLE lib, but what about the other libs?

BTW, I have a couple of improvements for the IN219 lib. We can make the value readout much faster (by more than one millisecond).  So I am definitely in for having the INA219 lib locally.

**Comment by thomastech** [comment]
> It seems that your .vscode/extensions.json is also causing trouble on Windows (different line endings). I think we should add .vscode to gitignore (and remove .vscode/extensions.json (but I have no idea what this file is good for). Apart from that it works.

I'm building on a Windows machine too. Are you sure it is safe to remove the extension manager file? 

> One question: why did you add the local copies of the INA219, BLE and XT libs. I saw you change something the BLE lib, but what about the other libs?

All of these libraries have custom patches. For example, the BLE library has my fixes for some pointer exception faults and semaphore hangs. I updated INA219 to allow very low value shunts. The XT DAC library has several improvements that I added {Xtronical's 4.2.1 release has incorporated them.} Long story short, for stability I recommend using my local libs.

> BTW, I have a couple of improvements for the IN219 lib. We can make the value readout much faster (by more than one millisecond). So I am definitely in for having the INA219 lib locally.

Sure, we can do whatever we want with the local libs.

- Thomas

**Comment by hogthrob** [comment]
No, I don't ask you to remove .vscode/extensions.json, I think the .vscode directory should be added to .gitignore.

**Comment by thomastech** [comment]
My initial concern was that untracking it (via .gitignore) might not be a good idea. That is to say, extensions.json wouldn't be automatically included in the repo.

But there is a happy ending. It turns out that Platformio recreates the file on each launch. So there's no need for the Sparky repo to include it. I'll add the .vscode/extensions.json to .gitignore on the next release.

BTW, I found something interesting related to this discussion. See this: https://github.com/platformio/platformio-vscode-ide/issues/922
The last post warns Platformio's current extensions.json behavior may lead to git conflicts due to differences in eol formatting. Platformio defaults to Windows CRLF, but it appears Git commit converts them to Unix LF. Sounds like the issue you are experiencing.

- Thomas

**Comment by thomastech** [comment]
.gitignore has been updated on the repo.

- Thomas
