### ISSUE TITLE
www.rc-cam.com no longer available, but archive available

### ISSUE THREAD

**Issue by RudyFiero** [thomastech/Sparky#9]
RC-CAM Forum has shutdown.
The RC-Cam forum has permanently closed.

Some of the information is available from the Wayback Machine internet archive.

https://web.archive.org/web/20201001184802/https://www.rc-cam.com/forum/index.php?/topic/4605-sparky-a-little-stick-welder-with-big-features/

**Comment by thomastech** [comment]
A link to a copy of the original build log is in the project's readme file. 
See the PDF file in this section:
https://github.com/thomastech/Sparky#skills-required
